### ISSUE TITLE
how to use modules imported?

### ISSUE THREAD

**Issue by rfyiamcool** [akerl-archived/modlib#15]
how to use modules imported?

**Comment by akerl** [comment]
I updated the readme to attempt to clarify this. Modstack's .get() method returns the module object (or the requested object from the module, if you use target=NAME). So if you have the following foobar.py:

```
def say_something(text):
    print(text)
```

You can do the following with modlib:

```
my_module = modlib.Modstack.get('foobar')
my_module.say_something('hello world')
```

If you use the "target" option, you can specifically pull the function or class you want:

```
my_method = modlib.Modstack(target='say_something').get('foobar')
method('hello world')
```
